### ISSUE TITLE
Error in mlts_transform: do not know how to convert 'x' to class “POSIXlt”

### ISSUE THREAD

**Issue by jbkunst** [bearloga/maltese#2]
Hi @bearloga ,

I have this example:
```r
data <- structure(list(x = c(70090.5778171204, 69356.3322413804, 67864.4479475701, 
                             68523.3096806297, 68298.0427100604, 64327.9984660899),
                       date = structure(c(1379894400, 1379980800, 1380067200, 1380153600,
                                          1380240000, 1380499200), class = c("POSIXct","POSIXt"))),
                  .Names = c("x", "date"), row.names = c(NA, -6L), class = c("tbl_df", "tbl", "data.frame"))

mlts <- mlts_transform(
  data, date, x,
  p = 2, # how many previous points of data to use as features
  granularity = "day", # optional, can be automatically detected,
  extras = TRUE, extrasAsFactors = TRUE # FALSE by default :D
)
```

And I have the next message:

```r
Error in as.POSIXlt.default(x, tz = tz(x)) : 
  do not know how to convert 'x' to class “POSIXlt”
In addition: Warning messages:
1: drop ignored 
2: drop ignored 
```

Not sure what is happening

One difference with the `r_enwiki` data, is  the date field is printed like a date, and in my example the data is printed like a date time value, anyway they have the same `"POSIXct" "POSIXt" ` class

Thanks in advance!

**Comment by bearloga** [comment]
Thanks for letting me know! Yeah, the problem was caused by the data being a tibble. It should work with tibbles now :)

**Comment by jbkunst** [comment]
Thanks so much @bearloga ! I will test now

**Comment by jbkunst** [comment]
A final comment, usually I use `tbl_df` class in the `.data` argument, and the output don't conserve that class (obviously because you make a new `data.frame`). Maybe is a nice detail for `dplyr` and `data.table` users if `mlts_transform` conserve the class of `.data`.

Cheers
